// Style profiles. Each style carries its own harmonic grammar, rhythmic vocabulary,
// textures, form, performance practice (rubato, pedalling, swing) and generator
// strategy, so switching style changes the compositional logic itself.

// Rhythm cells per pulse. Numbers are durations in quarters, negative = rest,
// 'T' as first element = tie (continue the previous note through this span).
export const RHYTHM_CELLS = {
  simple: {
    q: { c: [1], lvl: 1 },
    tie: { c: ['T', 1], lvl: 0 },
    rest: { c: [-1], lvl: 0 },
    e2: { c: [0.5, 0.5], lvl: 2 },
    dotted: { c: [0.75, 0.25], lvl: 2 },
    offbeat: { c: [-0.5, 0.5], lvl: 1.5 },
    syncop: { c: ['T', 0.5, 0.5], lvl: 1.5 },
    antic: { c: [0.5, 0.5], lvl: 2, tieNext: true },
    ess: { c: [0.5, 0.25, 0.25], lvl: 3 },
    sse: { c: [0.25, 0.25, 0.5], lvl: 3 },
    s4: { c: [0.25, 0.25, 0.25, 0.25], lvl: 4 },
    triplet: { c: [1 / 3, 1 / 3, 1 / 3], lvl: 3 },
  },
  compound: {
    q: { c: [1.5], lvl: 1 },
    tie: { c: ['T', 1.5], lvl: 0 },
    rest: { c: [-1.5], lvl: 0 },
    e2: { c: [1, 0.5], lvl: 2 },
    dotted: { c: [0.75, 0.25, 0.5], lvl: 3 },
    offbeat: { c: [-0.5, 0.5, 0.5], lvl: 2 },
    syncop: { c: [0.5, 1], lvl: 2 },
    antic: { c: [1, 0.5], lvl: 2, tieNext: true },
    ess: { c: [0.5, 0.5, 0.5], lvl: 3 },
    sse: { c: [0.25, 0.25, 0.5, 0.5], lvl: 4 },
    s4: { c: [0.25, 0.25, 0.25, 0.25, 0.5], lvl: 4.5 },
    triplet: { c: [0.5, 0.5, 0.5], lvl: 3 },
  },
};

const CLASSICAL = {
  id: 'classical',
  label: 'Classical',
  tempo: { min: 76, max: 144, default: 108 },
  meters: [[[4, 4], 5], [[3, 4], 3], [[2, 4], 1.5], [[6, 8], 1]],
  complexity: 0.5,
  minorBias: 0.35,
  modes: { major: ['major'], minor: ['minor'] },
  generator: 'functional',
  harmonicRhythm: { 1: 3, 2: 2 },
  progression: {
    major: {
      I: { IV: 3, V: 3, vi: 2, ii: 2, iii: 0.4, 'V/V': 0.6, 'V/vi': 0.4 },
      ii: { V: 5, 'vii°': 1, 'V/V': 0.8 },
      iii: { vi: 3, IV: 2, ii: 1 },
      IV: { V: 4, I: 2, ii: 2, 'vii°': 1 },
      V: { I: 6, vi: 1.5 },
      vi: { ii: 3, IV: 3, V: 1.5, iii: 0.5, 'V/V': 0.6 },
      'vii°': { I: 5 },
      'V/V': { V: 1 },
      'V/vi': { vi: 1 },
    },
    minor: {
      i: { iv: 3, V: 3, VI: 2.5, 'ii°': 1.5, III: 1.2, VII: 0.8 },
      'ii°': { V: 5, 'vii°': 1 },
      III: { VI: 2.5, iv: 2, VII: 1.2 },
      iv: { V: 4, i: 1.5, 'ii°': 1.5 },
      V: { i: 6, VI: 1.5 },
      VI: { iv: 2.5, 'ii°': 2, V: 1.5, III: 0.5 },
      VII: { III: 4, i: 0.5 },
      'vii°': { i: 5 },
    },
  },
  cadences: {
    major: {
      PAC: [['ii', 'V7', 'I'], ['IV', 'V', 'I'], ['V7', 'I'], ['vi', 'V7', 'I']],
      HC: [['ii', 'V'], ['IV', 'V'], ['I', 'V'], ['vi', 'V/V', 'V']],
      DC: [['IV', 'V7', 'vi'], ['V7', 'vi']],
      PLAGAL: [['IV', 'I']],
    },
    minor: {
      PAC: [['ii°', 'V7', 'i'], ['iv', 'V', 'i'], ['V7', 'i']],
      HC: [['iv', 'V'], ['ii°', 'V'], ['VI', 'V']],
      DC: [['iv', 'V7', 'VI'], ['V7', 'VI']],
      PLAGAL: [['iv', 'i']],
    },
  },
  extensions: { dominant7: 0.45, seventh: 0.12, ninth: 0, add9: 0, sus: 0.03, dim7: 0.35 },
  inversionProb: 0.25,
  voicing: { type: 'close', range: [52, 72], voices: 3 },
  bassRange: [36, 55],
  textures: {
    intro: { block: 2, alberti: 1 },
    theme: { alberti: 4, block: 1, waltz: 0 },
    development: { alberti: 2, broken: 2, octaves: 1 },
    climax: { octaves: 2, alberti: 2, broken: 1 },
    outro: { block: 2, alberti: 1 },
  },
  meterTextures: { 3: { waltz: 3 } },
  melody: {
    range: [67, 88], restProb: 0.08, stepBias: 1.3, leapMax: 9, repeatW: 0.35,
    appoggiatura: 0.12, chromatic: 0.03, octaveDouble: 0,
    rhythm: { q: 3, e2: 3, dotted: 1.5, sse: 1, ess: 1, s4: 0.5, tie: 0.8, rest: 0.2, triplet: 0.2, syncop: 0.15 },
    baseLevel: 1.6,
    contours: { arch: 3, ascending: 1, descending: 1.5, wave: 1 },
    degreeWeights: [1.3, 1, 1.15, 0.9, 1.2, 0.95, 0.8],
  },
  dynamics: { min: 42, max: 100, hairpin: 12 },
  rubato: 0.03, sectionRit: 0.08, finalRit: 0.22, swing: 0,
  pedal: 'chord',
  form: [
    { type: 'intro', name: 'Introduction', weight: 0.5, fixed: 1 },
    { type: 'theme', name: 'Exposition', weight: 2, min: 2 },
    { type: 'development', name: 'Development', weight: 1.6, min: 1 },
    { type: 'climax', name: 'Recapitulation', weight: 1.6, min: 1, reuse: 'theme' },
    { type: 'outro', name: 'Coda', weight: 0.5, fixed: 1 },
  ],
  keyPlan: { major: { development: [7, 'major'], alt: [9, 'minor'] }, minor: { development: [3, 'major'], alt: [7, 'minor'] } },
  titles: ['Sonatina', 'Rondino', 'Allegretto', 'Divertimento', 'Andante', 'Sonata movement'],
  techniques: ['periodic phrasing (antecedent/consequent)', 'Alberti bass', 'sonata-style recapitulation', 'modulation to the dominant/relative key'],
};

const BAROQUE = {
  id: 'baroque',
  label: 'Baroque',
  tempo: { min: 72, max: 132, default: 96 },
  meters: [[[4, 4], 5], [[3, 4], 2], [[12, 8], 0.8], [[6, 8], 0.8]],
  complexity: 0.6,
  minorBias: 0.5,
  modes: { major: ['major'], minor: ['minor'] },
  generator: 'functional',
  harmonicRhythm: { 2: 3, 1: 2 },
  progression: {
    major: {
      I: { IV: 2.5, V: 2.5, vi: 2, ii: 1.5, 'V/V': 0.8, 'V/vi': 0.6, 'V/ii': 0.4, iii: 0.5 },
      IV: { 'vii°': 2.5, V: 3, ii: 1.5, I: 1 },
      'vii°': { iii: 2, I: 3 },
      iii: { vi: 4, IV: 1 },
      vi: { ii: 4, IV: 1.5, V: 1, 'V/ii': 0.4 },
      ii: { V: 5, 'vii°': 1 },
      V: { I: 5, vi: 1.5 },
      'V/V': { V: 1 }, 'V/vi': { vi: 1 }, 'V/ii': { ii: 1 },
    },
    minor: {
      i: { iv: 3, VII: 2, V: 2.5, VI: 1.5, 'ii°': 1 },
      iv: { VII: 2.5, V: 3, 'ii°': 1.5 },
      VII: { III: 4 },
      III: { VI: 3.5, iv: 1 },
      VI: { 'ii°': 3, iv: 2, V: 1 },
      'ii°': { V: 5 },
      V: { i: 5, VI: 1 },
    },
  },
  sequences: {
    major: [['I', 'IV', 'vii°', 'iii', 'vi', 'ii', 'V', 'I'], ['I', 'V/vi', 'vi', 'V/V', 'V', 'V/ii', 'ii', 'V']],
    minor: [['i', 'iv', 'VII', 'III', 'VI', 'ii°', 'V', 'i']],
  },
  cadences: {
    major: { PAC: [['ii', 'V7', 'I'], ['IV', 'V7', 'I']], HC: [['ii', 'V'], ['IV', 'V']], DC: [['V7', 'vi']], PLAGAL: [['IV', 'I']] },
    minor: { PAC: [['ii°', 'V7', 'i'], ['iv', 'V7', 'i']], HC: [['iv', 'V']], DC: [['V7', 'VI']], PLAGAL: [['iv', 'I']] },
  },
  extensions: { dominant7: 0.6, seventh: 0.3, ninth: 0, add9: 0, sus: 0.05, dim7: 0.2 },
  inversionProb: 0.35,
  voicing: { type: 'close', range: [53, 72], voices: 3 },
  bassRange: [36, 57],
  textures: {
    intro: { continuo: 1 }, theme: { continuo: 1 }, development: { continuo: 1 },
    climax: { continuo: 1 }, outro: { continuo: 1 },
  },
  counterpoint: true, // harmony layer is an independent inner voice
  melody: {
    range: [64, 86], restProb: 0.02, stepBias: 1.6, leapMax: 9, repeatW: 0.2,
    appoggiatura: 0.05, chromatic: 0.02, octaveDouble: 0,
    rhythm: { e2: 4, s4: 3, ess: 2, sse: 2, q: 1, dotted: 1, tie: 0.15, rest: 0.03 },
    baseLevel: 2.6,
    contours: { wave: 3, descending: 2, arch: 1.5, ascending: 1 },
    degreeWeights: [1.2, 1, 1.1, 1, 1.15, 1, 0.9],
    sequenceProb: 0.6,
  },
  dynamics: { min: 55, max: 92, hairpin: 5, terraced: true },
  rubato: 0.0, sectionRit: 0.1, finalRit: 0.2, swing: 0,
  pedal: 'none',
  form: [
    { type: 'intro', name: 'Ritornello', weight: 0.6, fixed: 1 },
    { type: 'theme', name: 'Exposition', weight: 1.6, min: 1 },
    { type: 'development', name: 'Episodes (sequences)', weight: 2, min: 2 },
    { type: 'climax', name: 'Ritornello in tonic', weight: 1.4, min: 1, reuse: 'theme' },
    { type: 'outro', name: 'Closing', weight: 0.5, fixed: 1 },
  ],
  keyPlan: { major: { development: [7, 'major'], alt: [9, 'minor'] }, minor: { development: [3, 'major'], alt: [7, 'minor'] } },
  titles: ['Invention', 'Prelude', 'Sinfonia', 'Toccata', 'Gigue', 'Allemande'],
  techniques: ['Fortspinnung (motif spun out by sequence)', 'circle-of-fifths sequences', 'walking continuo bass', 'three-voice counterpoint'],
};

const ROMANTIC = {
  id: 'romantic',
  label: 'Romantic',
  tempo: { min: 52, max: 120, default: 72 },
  meters: [[[4, 4], 3], [[3, 4], 3], [[6, 8], 2], [[12, 8], 1]],
  complexity: 0.6,
  minorBias: 0.5,
  modes: { major: ['major'], minor: ['minor'] },
  generator: 'functional',
  harmonicRhythm: { 1: 4, 2: 1.5, 0.5: 0.5 },
  progression: {
    major: {
      I: { IV: 2, vi: 2, V: 2, ii: 1.5, iii: 1, 'V/vi': 0.8, bVI: 0.8, iv: 0.8, III: 0.5, 'V/ii': 0.5 },
      ii: { V: 4, 'vii°7': 1, 'V/V': 1 },
      iii: { vi: 2.5, IV: 2 },
      IV: { iv: 1.5, V: 2.5, I: 1.5, ii: 1, 'vii°7': 0.5 },
      iv: { I: 2.5, V: 2 },
      V: { I: 5, vi: 2, bVI: 0.6 },
      vi: { IV: 2.5, ii: 2.5, iii: 1, V: 1, 'V/V': 1 },
      bVI: { iv: 1.5, V: 2, I: 1.5, bII: 0.4 },
      III: { vi: 2, IV: 1.5, I: 1 },
      'vii°7': { I: 4 },
      bII: { V: 3 },
      'V/V': { V: 1 }, 'V/vi': { vi: 1 }, 'V/ii': { ii: 1 },
    },
    minor: {
      i: { iv: 2.5, VI: 2.5, V: 2, III: 1.5, bII: 0.7, 'ii°': 1, VII: 1, 'vii°7': 0.8, 'V/iv': 0.6 },
      iv: { V: 3, i: 1.5, 'vii°7': 1.2, bII: 1, VII: 0.8 },
      bII: { V: 4 },
      VI: { iv: 1.5, bII: 1.2, 'ii°': 1.5, V: 1.5, III: 0.8 },
      III: { VI: 2, iv: 1.5, VII: 1, 'V/iv': 0.5 },
      VII: { III: 3, i: 0.5 },
      'ii°': { V: 5 },
      V: { i: 5, VI: 2 },
      'vii°7': { i: 4, V: 0.8 },
      'V/iv': { iv: 1 },
    },
  },
  cadences: {
    major: {
      PAC: [['iv', 'V7', 'I'], ['ii7', 'V7', 'I'], ['bVI', 'V7', 'I'], ['IV', 'vii°7', 'I']],
      HC: [['iv', 'V'], ['ii', 'V/V', 'V'], ['bVI', 'V']],
      DC: [['V7', 'bVI'], ['V7', 'vi']],
      PLAGAL: [['iv', 'I'], ['IV', 'iv', 'I']],
    },
    minor: {
      PAC: [['bII', 'V7', 'i'], ['iv', 'V7', 'i'], ['VI', 'vii°7', 'i']],
      HC: [['iv', 'V'], ['bII', 'V'], ['VI', 'V']],
      DC: [['V7', 'VI']],
      PLAGAL: [['iv', 'i']],
    },
  },
  extensions: { dominant7: 0.55, seventh: 0.3, ninth: 0.15, add9: 0.08, sus: 0.05, dim7: 0.5 },
  inversionProb: 0.2,
  voicing: { type: 'open', range: [50, 76], voices: 3 },
  bassRange: [28, 52],
  textures: {
    intro: { arpeggio: 3, block: 1 },
    theme: { arpeggio: 4, waltz: 0, block: 0.5 },
    development: { arpeggio: 3, broken: 1.5, octaves: 0.5 },
    climax: { arpeggio: 2, octaves: 2, block: 1 },
    outro: { arpeggio: 2, block: 1.5 },
  },
  meterTextures: { 3: { waltz: 2, arpeggio: 2 } },
  melody: {
    range: [62, 91], restProb: 0.05, stepBias: 1.0, leapMax: 12, repeatW: 0.3,
    appoggiatura: 0.25, chromatic: 0.08, octaveDouble: 0.9,
    rhythm: { q: 3, tie: 2, e2: 2, triplet: 1.5, dotted: 1.5, s4: 0.4, rest: 0.3, syncop: 0.4 },
    baseLevel: 1.4,
    contours: { arch: 4, ascending: 1.2, descending: 1.2, wave: 1 },
    degreeWeights: [1.1, 1, 1.2, 0.95, 1.2, 1.05, 0.85],
  },
  dynamics: { min: 34, max: 112, hairpin: 18 },
  rubato: 0.09, sectionRit: 0.12, finalRit: 0.35, swing: 0,
  pedal: 'chord',
  form: [
    { type: 'intro', name: 'Introduction', weight: 0.5, fixed: 1 },
    { type: 'theme', name: 'Theme', weight: 2, min: 2 },
    { type: 'development', name: 'Agitato (development)', weight: 1.6, min: 1 },
    { type: 'climax', name: 'Climax — theme returns', weight: 1.4, min: 1, reuse: 'theme' },
    { type: 'outro', name: 'Coda', weight: 0.6, fixed: 1 },
  ],
  keyPlan: { major: { development: [8, 'major'], alt: [9, 'minor'] }, minor: { development: [8, 'major'], alt: [3, 'major'] } },
  titles: ['Nocturne', 'Romance', 'Intermezzo', 'Ballade', 'Song Without Words', 'Impromptu'],
  techniques: ['modal mixture (borrowed iv, ♭VI)', 'Neapolitan and diminished-seventh colour', 'wide arpeggiated accompaniment', 'expressive rubato', 'appoggiaturas'],
};

const JAZZ = {
  id: 'jazz',
  label: 'Jazz',
  tempo: { min: 60, max: 176, default: 112 },
  meters: [[[4, 4], 8], [[3, 4], 1]],
  complexity: 0.6,
  minorBias: 0.35,
  modes: { major: ['major'], minor: ['minor'] },
  generator: 'functional',
  harmonicRhythm: { 1: 4, 2: 2 },
  progression: {
    major: {
      Imaj7: { vi7: 2.5, ii7: 3, IVmaj7: 1.5, iii7: 1, 'V7/ii': 1.5, 'V7/IV': 0.8 },
      ii7: { V7: 6, bII7: 1.2 },
      iii7: { vi7: 2.5, 'V7/ii': 1.5 },
      IVmaj7: { iv7: 1, iii7: 1.5, V7: 1, ii7: 1.5, bVII7: 1 },
      iv7: { Imaj7: 1, bVII7: 1.5 },
      bVII7: { Imaj7: 1 },
      V7: { Imaj7: 5, vi7: 1, iii7: 0.5 },
      bII7: { Imaj7: 1 },
      vi7: { ii7: 4, 'V7/ii': 1, IVmaj7: 1 },
      'V7/ii': { ii7: 1 },
      'V7/IV': { IVmaj7: 1 },
      'V7/V': { ii7: 1, V7: 1 },
    },
    minor: {
      i6: { 'iiø7': 3, iv7: 2.5, VImaj7: 1.5, IIImaj7: 1, 'V7/iv': 0.8 },
      'iiø7': { V7b9: 6 },
      iv7: { V7b9: 2, VII7: 2, 'iiø7': 1.5, i6: 1 },
      VImaj7: { 'iiø7': 2.5, V7b9: 1, iv7: 1 },
      IIImaj7: { VImaj7: 2, iv7: 1.5, 'iiø7': 1 },
      VII7: { IIImaj7: 3 },
      V7b9: { i6: 5, VImaj7: 1 },
      'V7/iv': { iv7: 1 },
    },
  },
  cadences: {
    major: {
      PAC: [['ii7', 'V7', 'Imaj7'], ['vi7', 'ii7', 'V7', 'Imaj7'], ['ii7', 'bII7', 'Imaj7']],
      HC: [['ii7', 'V7'], ['vi7', 'ii7', 'V7']],
      DC: [['ii7', 'V7', 'vi7']],
      PLAGAL: [['iv7', 'bVII7', 'Imaj7']],
      TURN: [['Imaj7', 'vi7', 'ii7', 'V7']],
    },
    minor: {
      PAC: [['iiø7', 'V7b9', 'i6']],
      HC: [['iiø7', 'V7b9']],
      DC: [['iiø7', 'V7b9', 'VImaj7']],
      PLAGAL: [['iv7', 'VII7', 'i6']],
      TURN: [['i6', 'VImaj7', 'iiø7', 'V7b9']],
    },
  },
  extensions: { dominant7: 1, seventh: 1, ninth: 0.55, thirteenth: 0.3, add9: 0, sus: 0.04, dim7: 0 },
  inversionProb: 0,
  voicing: { type: 'rootless', range: [50, 72], voices: 4 },
  bassRange: [36, 55],
  textures: {
    intro: { comp: 1 }, theme: { comp: 1 }, development: { comp: 1 }, climax: { comp: 1 }, outro: { comp: 1 },
  },
  melody: {
    range: [62, 84], restProb: 0.12, stepBias: 1.1, leapMax: 9, repeatW: 0.3,
    appoggiatura: 0.05, chromatic: 0.28, octaveDouble: 0, blueNotes: 0.1,
    rhythm: { e2: 4, syncop: 2.5, offbeat: 1.5, q: 2, tie: 1, rest: 1.2, triplet: 1, antic: 1.2, dotted: 0.3, s4: 0.15 },
    baseLevel: 1.9,
    contours: { wave: 3, arch: 2, descending: 1.5, ascending: 1 },
    degreeWeights: [1, 1.1, 1.3, 0.9, 1.1, 1.1, 1.15],
    guideTones: true,
  },
  dynamics: { min: 48, max: 98, hairpin: 8 },
  rubato: 0.0, sectionRit: 0.0, finalRit: 0.18, swing: 0.16,
  pedal: 'light',
  form: [
    { type: 'intro', name: 'Intro vamp', weight: 0.5, fixed: 1 },
    { type: 'theme', name: 'Head (AABA)', weight: 2, min: 2, jazzHead: true },
    { type: 'development', name: 'Improvised chorus', weight: 2, min: 1, reuseHarmony: 'theme' },
    { type: 'climax', name: 'Head out', weight: 1.4, min: 1, reuse: 'theme' },
    { type: 'outro', name: 'Tag ending', weight: 0.5, fixed: 1 },
  ],
  keyPlan: null,
  titles: ['Ballad', 'Blue Hour', 'After Hours', 'Late Set', 'Corner Table', 'Nightcap'],
  techniques: ['ii–V–I cadences and tritone substitution', 'rootless A/B voicings', 'walking bass with chromatic approach', 'swing feel', 'AABA head with improvised chorus'],
};

const AMBIENT = {
  id: 'ambient',
  label: 'Ambient',
  tempo: { min: 50, max: 84, default: 64 },
  meters: [[[4, 4], 5], [[3, 4], 1.5], [[6, 8], 1]],
  complexity: 0.3,
  minorBias: 0.45,
  modes: { major: ['major', 'lydian', 'mixolydian'], minor: ['minor', 'dorian'] },
  generator: 'modal',
  harmonicRhythm: { 0.5: 4, 1: 1.5 },
  progression: {
    major: {
      Iadd9: { IVmaj7: 3, vi7: 2, iii7: 1, Vsus4: 1, bVIIadd9: 0.8, ii7: 1, IIadd9: 0.8 },
      IVmaj7: { Iadd9: 3, vi7: 1.5, ii7: 1, Vsus4: 1 },
      vi7: { IVmaj7: 3, Iadd9: 1.5, iii7: 1, ii7: 1 },
      iii7: { vi7: 2, IVmaj7: 2 },
      ii7: { IVmaj7: 1.5, Vsus4: 1.5, Iadd9: 1 },
      Vsus4: { Iadd9: 2, vi7: 1.5, IVmaj7: 1 },
      bVIIadd9: { IVmaj7: 1.5, Iadd9: 2 },
      IIadd9: { Iadd9: 2, vi7: 1 },
    },
    minor: {
      iadd9: { VImaj7: 3, IIImaj7: 1.5, iv7: 1.5, VIIadd9: 1.5, v7: 1, IVadd9: 0.8 },
      VImaj7: { IIImaj7: 2, iadd9: 2, VIIadd9: 1.5, iv7: 1 },
      IIImaj7: { VImaj7: 1.5, VIIadd9: 2, iv7: 1 },
      VIIadd9: { iadd9: 2.5, IIImaj7: 1.5, VImaj7: 1 },
      iv7: { iadd9: 2, VImaj7: 1.5, v7: 1 },
      v7: { iadd9: 2, VImaj7: 1 },
      IVadd9: { iadd9: 2, v7: 1 },
    },
  },
  cadences: {
    major: { PAC: [['IVmaj7', 'Iadd9'], ['bVIIadd9', 'Iadd9']], HC: [['vi7', 'IVmaj7'], ['ii7', 'Vsus4']], DC: [['Vsus4', 'vi7']], PLAGAL: [['IVmaj7', 'Iadd9']] },
    minor: { PAC: [['VIIadd9', 'iadd9'], ['iv7', 'iadd9']], HC: [['VImaj7', 'VIIadd9'], ['iv7', 'v7']], DC: [['VIIadd9', 'VImaj7']], PLAGAL: [['iv7', 'iadd9']] },
  },
  extensions: { dominant7: 0, seventh: 0.2, ninth: 0.1, add9: 0.3, sus: 0.15, dim7: 0 },
  inversionProb: 0.1,
  pedalPoint: 0.45,
  voicing: { type: 'spread', range: [50, 79], voices: 4 },
  bassRange: [28, 48],
  textures: {
    intro: { pad: 3, shimmer: 1 }, theme: { pad: 2, shimmer: 2 }, development: { shimmer: 2, pad: 1.5 },
    climax: { shimmer: 2, pad: 1 }, outro: { pad: 3 },
  },
  melody: {
    range: [64, 86], restProb: 0.35, stepBias: 1.0, leapMax: 9, repeatW: 0.5,
    appoggiatura: 0.02, chromatic: 0, octaveDouble: 0, echo: 0.5,
    rhythm: { tie: 4, q: 2, rest: 3, e2: 0.4, dotted: 0.3, offbeat: 0.5 },
    baseLevel: 0.5,
    contours: { wave: 3, arch: 2, descending: 1 },
    degreeWeights: [1.3, 1.1, 1.2, 0.35, 1.2, 1.1, 0.35],
  },
  dynamics: { min: 34, max: 80, hairpin: 10 },
  rubato: 0.04, sectionRit: 0.05, finalRit: 0.3, swing: 0,
  pedal: 'long',
  form: [
    { type: 'intro', name: 'Emergence', weight: 0.8, fixed: 1 },
    { type: 'theme', name: 'Drift', weight: 2, min: 1 },
    { type: 'development', name: 'Shift', weight: 1.4, min: 1 },
    { type: 'climax', name: 'Swell', weight: 1.4, min: 1, reuseHarmony: 'theme' },
    { type: 'outro', name: 'Dissolve', weight: 0.8, fixed: 1 },
  ],
  keyPlan: { major: { development: [0, 'lydian'] }, minor: { development: [0, 'dorian'] } },
  titles: ['Drift', 'Stillwater', 'Low Cloud', 'Glasshouse', 'Afterglow', 'Tidal'],
  techniques: ['modal harmony without dominant pull', 'pedal points', 'add9 / maj7 colour chords', 'sustained pads with long pedal', 'sparse echoing melody'],
};

const MINIMALIST = {
  id: 'minimalist',
  label: 'Minimalist',
  tempo: { min: 96, max: 160, default: 126 },
  meters: [[[4, 4], 4], [[6, 8], 1.5], [[3, 4], 1], [[7, 8], 0.8], [[5, 4], 0.6]],
  complexity: 0.5,
  minorBias: 0.45,
  modes: { major: ['major', 'lydian'], minor: ['minor', 'dorian'] },
  generator: 'cycle',
  harmonicRhythm: { 0.5: 2, 1: 3 },
  cyclePool: {
    major: ['I', 'vi', 'IV', 'iii', 'ii', 'Vsus4', 'Iadd9', 'IVadd9'],
    minor: ['i', 'VI', 'III', 'VII', 'iv', 'v', 'iadd9', 'VImaj7'],
  },
  extensions: { dominant7: 0, seventh: 0.1, ninth: 0, add9: 0.15, sus: 0.1, dim7: 0 },
  inversionProb: 0.2,
  pedalPoint: 0.35,
  voicing: { type: 'close', range: [55, 76], voices: 3 },
  bassRange: [33, 52],
  textures: { intro: { ostinato: 1 }, theme: { ostinato: 1 }, development: { ostinato: 1 }, climax: { ostinato: 1 }, outro: { ostinato: 1 } },
  melody: {
    range: [64, 84], restProb: 0, stepBias: 1, leapMax: 12, repeatW: 1,
    appoggiatura: 0, chromatic: 0, octaveDouble: 0,
    rhythm: { e2: 1 }, baseLevel: 2, contours: { wave: 1 },
    degreeWeights: [1, 1, 1, 1, 1, 1, 1],
  },
  dynamics: { min: 44, max: 96, hairpin: 4, terraced: true },
  rubato: 0, sectionRit: 0, finalRit: 0.08, swing: 0,
  pedal: 'chord',
  form: [
    { type: 'intro', name: 'Cell (additive)', weight: 1, fixed: 1 },
    { type: 'theme', name: 'Process A', weight: 2, min: 1 },
    { type: 'development', name: 'Phase shift', weight: 2, min: 1 },
    { type: 'climax', name: 'Full texture', weight: 1.5, min: 1 },
    { type: 'outro', name: 'Subtractive fade', weight: 1, fixed: 1 },
  ],
  keyPlan: null,
  titles: ['Process', 'Pulse Study', 'Cells', 'Phases', 'Loop Field', 'Additive Music'],
  techniques: ['repeating chord cycles', 'additive/subtractive process', 'phase-shifted ostinato', 'polymetric layers', 'terraced dynamics'],
};

const CONTEMPORARY = {
  id: 'contemporary',
  label: 'Contemporary',
  tempo: { min: 56, max: 132, default: 84 },
  meters: [[[4, 4], 4], [[3, 4], 1.5], [[5, 4], 1], [[7, 8], 1], [[6, 8], 1]],
  complexity: 0.6,
  minorBias: 0.5,
  modes: { major: ['lydian', 'major', 'mixolydian'], minor: ['dorian', 'minor', 'phrygian'] },
  generator: 'neoRiemannian',
  harmonicRhythm: { 1: 3, 0.5: 1.5, 2: 0.8 },
  extensions: { dominant7: 0, seventh: 0.3, ninth: 0.1, add9: 0.45, sus: 0.2, dim7: 0, sharp11: 0.15 },
  inversionProb: 0.3,
  pedalPoint: 0.2,
  voicing: { type: 'quartal', range: [48, 79], voices: 4 },
  bassRange: [28, 52],
  textures: {
    intro: { wash: 2, pulse: 1 }, theme: { pulse: 2, arpeggio: 1.5, wash: 1 }, development: { pulse: 2.5, arpeggio: 1 },
    climax: { pulse: 2, octaves: 1, arpeggio: 1 }, outro: { wash: 3 },
  },
  melody: {
    range: [60, 91], restProb: 0.15, stepBias: 0.8, leapMax: 12, repeatW: 0.4,
    appoggiatura: 0.1, chromatic: 0.05, octaveDouble: 0.6, quartal: 0.35,
    rhythm: { q: 2, e2: 2, rest: 1.5, tie: 1.5, offbeat: 1, syncop: 1, s4: 0.8, triplet: 0.8, dotted: 1, sse: 1 },
    baseLevel: 1.6,
    contours: { ascending: 2, wave: 2, arch: 2, descending: 1 },
    degreeWeights: [1.2, 1.1, 1.1, 1, 1.2, 1.1, 1],
  },
  dynamics: { min: 30, max: 108, hairpin: 16 },
  rubato: 0.05, sectionRit: 0.08, finalRit: 0.3, swing: 0,
  pedal: 'chord',
  form: [
    { type: 'intro', name: 'Opening', weight: 0.6, fixed: 1 },
    { type: 'theme', name: 'Statement', weight: 1.8, min: 1 },
    { type: 'development', name: 'Transformation', weight: 1.8, min: 1 },
    { type: 'climax', name: 'Climax', weight: 1.4, min: 1, reuse: 'theme' },
    { type: 'outro', name: 'Epilogue', weight: 0.7, fixed: 1 },
  ],
  keyPlan: { major: { development: [4, 'lydian'] }, minor: { development: [8, 'dorian'] } },
  titles: ['Refractions', 'Thresholds', 'Lines in Light', 'Coastline', 'Parallax', 'Transit'],
  techniques: ['neo-Riemannian (P/L/R) chord transformations', 'modal colour (Lydian/Dorian)', 'quartal and open-fifth voicings', 'irregular meters and syncopation'],
};

export const STYLES = {
  classical: CLASSICAL,
  baroque: BAROQUE,
  romantic: ROMANTIC,
  jazz: JAZZ,
  ambient: AMBIENT,
  minimalist: MINIMALIST,
  contemporary: CONTEMPORARY,
};

export const STYLE_IDS = Object.keys(STYLES);

export function getStyle(id) {
  return STYLES[id] || STYLES.classical;
}
